/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report process and database state.
         *
         *     Defined with `def` rather than `async def` on purpose: FastAPI runs synchronous
         *     endpoints in a threadpool, which lets the whole library stay synchronous and keeps
         *     the API and the eval runner on one code path.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Default Config
         * @description The retrieval defaults, as the library defines them.
         *
         *     The config panel initialises itself from this rather than hard-coding the same numbers
         *     in TypeScript. Restating them client-side would mean the front end could quietly
         *     disagree with the library about what "default" means -- and the whole point of the
         *     single frozen config object is that there is one answer to that question.
         */
        get: operations["default_config_config_default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve Only
         * @description Run retrieval and return the ranked chunks, without generating an answer.
         *
         *     Exists because the most convincing thing this system can show a technical visitor --
         *     toggling reranking and watching the results reorder -- is a property of retrieval
         *     alone. Routing that through generation would spend money and add a network dependency
         *     to a demonstration that needs neither, and would make the interesting part slower and
         *     harder to see.
         *
         *     It is also what lets the whole front end work on a deployment with no model
         *     credentials at all.
         */
        post: operations["retrieve_only_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query
         * @description Answer a question from the indexed corpus, or refuse.
         *
         *     Synchronous, so it shares the library's single code path with the eval runner.
         */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Stream
         * @description Answer a question as a token stream, ending with a citations event.
         *
         *     Retrieval runs to completion before the first token, because the citation markers a
         *     client renders are only meaningful once it knows which sources they number. The
         *     stages event is emitted first so the UI can show "searching / reranking / generating"
         *     against real timings rather than a spinner.
         *
         *     A refusal streams the refusal sentence and no tokens are ever bought for it.
         */
        get: operations["query_stream_query_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CitedSentence
         * @description One sentence of the answer with the chunks it cited.
         */
        CitedSentence: {
            /** Text */
            text: string;
            /** Chunk Ids */
            chunk_ids: number[];
        };
        /**
         * DatabaseHealth
         * @description What the process can currently observe about its database.
         */
        DatabaseHealth: {
            /** Connected */
            connected: boolean;
            /** Server Version */
            server_version?: string | null;
            /** Pgvector Version */
            pgvector_version?: string | null;
            /** Applied Migrations */
            applied_migrations?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * GenerationConfig
         * @description Everything configurable about turning retrieved context into an answer.
         *
         *     Separate from `RetrievalConfig` deliberately. That model is the ablation axis for
         *     retrieval, and its every field is swept by the Phase 7 matrix; generation has its own
         *     axes -- model, temperature, prompt version -- which vary independently. Folding them
         *     together would make each retrieval arm carry fields that had nothing to do with it,
         *     and would misname the thing. An evaluation result embeds both.
         */
        GenerationConfig: {
            /**
             * Provider
             * @default anthropic
             * @enum {string}
             */
            provider: "anthropic" | "openai_compatible";
            /**
             * Model
             * @default claude-haiku-4-5
             */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
            /**
             * Max Tokens
             * @default 1024
             */
            max_tokens: number;
            /**
             * Prompt Version
             * @default v1
             */
            prompt_version: string;
            /**
             * Max Citation Retries
             * @default 1
             */
            max_citation_retries: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Payload for GET /health.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            db: components["schemas"]["DatabaseHealth"];
            /** Version */
            version: string;
            /** Generation Configured */
            generation_configured: boolean;
        };
        /**
         * QueryRequest
         * @description Body for POST /query.
         *
         *     Retrieval and generation settings are accepted per request so the Phase 8 config
         *     panel can toggle reranking and fusion and show the effect live. They default to the
         *     same values the eval harness uses, so the demo and the measurements describe one
         *     system.
         */
        QueryRequest: {
            /** Question */
            question: string;
            /**
             * @default {
             *       "embedding_model": "BAAI/bge-small-en-v1.5",
             *       "chunk_tokens": 512,
             *       "chunk_overlap_pct": 0.15,
             *       "drop_references": true,
             *       "drop_figure_only_pages": true,
             *       "contextual_headers": true,
             *       "dense_enabled": true,
             *       "dense_top_k": 50,
             *       "hnsw_ef_search": 400,
             *       "lexical_enabled": true,
             *       "lexical_top_k": 50,
             *       "fusion": "rrf",
             *       "rrf_k": 60,
             *       "rerank_enabled": true,
             *       "rerank_model": "BAAI/bge-reranker-base",
             *       "rerank_top_n": 50,
             *       "final_top_k": 5,
             *       "score_floor": 0.05
             *     }
             */
            config: components["schemas"]["RetrievalConfig"];
            /**
             * @default {
             *       "provider": "anthropic",
             *       "model": "claude-haiku-4-5",
             *       "temperature": 0,
             *       "max_tokens": 1024,
             *       "prompt_version": "v1",
             *       "max_citation_retries": 1
             *     }
             */
            generation: components["schemas"]["GenerationConfig"];
        };
        /**
         * QueryResponse
         * @description Payload for POST /query.
         */
        QueryResponse: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Refused */
            refused: boolean;
            /** Refusal Reason */
            refusal_reason: string | null;
            /** Uncited */
            uncited: boolean;
            /** Sentences */
            sentences: components["schemas"]["CitedSentence"][];
            /** Sources */
            sources: components["schemas"]["SourceBlock"][];
            /** Cited Chunk Ids */
            cited_chunk_ids: number[];
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Llm Calls */
            llm_calls: number;
            /** Query Log Id */
            query_log_id: number | null;
        };
        /**
         * RetrievalConfig
         * @description One point in the retrieval configuration space.
         *
         *     Nothing in the retrieval path may read an environment variable; if a knob affects
         *     what gets retrieved, it belongs here so that it is captured in the result record.
         *     Process-level concerns such as the database URL live in `rag.settings` instead.
         */
        RetrievalConfig: {
            /**
             * Embedding Model
             * @default BAAI/bge-small-en-v1.5
             */
            embedding_model: string;
            /**
             * Chunk Tokens
             * @default 512
             */
            chunk_tokens: number;
            /**
             * Chunk Overlap Pct
             * @default 0.15
             */
            chunk_overlap_pct: number;
            /**
             * Drop References
             * @default true
             */
            drop_references: boolean;
            /**
             * Drop Figure Only Pages
             * @default true
             */
            drop_figure_only_pages: boolean;
            /**
             * Contextual Headers
             * @default true
             */
            contextual_headers: boolean;
            /**
             * Dense Enabled
             * @default true
             */
            dense_enabled: boolean;
            /**
             * Dense Top K
             * @default 50
             */
            dense_top_k: number;
            /**
             * Hnsw Ef Search
             * @default 400
             */
            hnsw_ef_search: number;
            /**
             * Lexical Enabled
             * @default true
             */
            lexical_enabled: boolean;
            /**
             * Lexical Top K
             * @default 50
             */
            lexical_top_k: number;
            /**
             * Fusion
             * @default rrf
             * @enum {string}
             */
            fusion: "rrf" | "dense_only" | "lexical_only";
            /**
             * Rrf K
             * @default 60
             */
            rrf_k: number;
            /**
             * Rerank Enabled
             * @default true
             */
            rerank_enabled: boolean;
            /**
             * Rerank Model
             * @default BAAI/bge-reranker-base
             */
            rerank_model: string;
            /**
             * Rerank Top N
             * @default 50
             */
            rerank_top_n: number;
            /**
             * Final Top K
             * @default 5
             */
            final_top_k: number;
            /**
             * Score Floor
             * @default 0.05
             */
            score_floor: number;
        };
        /**
         * RetrieveRequest
         * @description Body for POST /retrieve.
         */
        RetrieveRequest: {
            /** Question */
            question: string;
            /**
             * @default {
             *       "embedding_model": "BAAI/bge-small-en-v1.5",
             *       "chunk_tokens": 512,
             *       "chunk_overlap_pct": 0.15,
             *       "drop_references": true,
             *       "drop_figure_only_pages": true,
             *       "contextual_headers": true,
             *       "dense_enabled": true,
             *       "dense_top_k": 50,
             *       "hnsw_ef_search": 400,
             *       "lexical_enabled": true,
             *       "lexical_top_k": 50,
             *       "fusion": "rrf",
             *       "rrf_k": 60,
             *       "rerank_enabled": true,
             *       "rerank_model": "BAAI/bge-reranker-base",
             *       "rerank_top_n": 50,
             *       "final_top_k": 5,
             *       "score_floor": 0.05
             *     }
             */
            config: components["schemas"]["RetrievalConfig"];
        };
        /**
         * RetrieveResponse
         * @description Payload for POST /retrieve: what retrieval found, and what it cost.
         */
        RetrieveResponse: {
            /** Question */
            question: string;
            /** Sources */
            sources: components["schemas"]["SourceBlock"][];
            /** Refused */
            refused: boolean;
            /** Reason */
            reason: string | null;
            /** Dense Count */
            dense_count: number;
            /** Lexical Count */
            lexical_count: number;
            /** Fused Count */
            fused_count: number;
            /** Reranked */
            reranked: number | null;
            /** Mean Rank Movement */
            mean_rank_movement: number | null;
            /** Timings Ms */
            timings_ms: {
                [key: string]: number;
            };
        };
        /**
         * SourceBlock
         * @description A retrieved chunk, in the numbering the answer's markers refer to.
         */
        SourceBlock: {
            /** Marker */
            marker: number;
            /** Chunk Id */
            chunk_id: number;
            /** Paper Id */
            paper_id: string;
            /** Paper Title */
            paper_title: string;
            /** Section Path */
            section_path: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Rerank Score */
            rerank_score?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    default_config_config_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalConfig"];
                };
            };
        };
    };
    retrieve_only_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_stream_query_stream_get: {
        parameters: {
            query: {
                question: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
